(function(){'use strict';
const cfg=window.MATHQUEST_FIREBASE_CONFIG||{};let db,auth,rows=[];const grades=['pre1','pre2','g1','g2','g3','g4','g5'];const labels={pre1:'Pré I',pre2:'Pré II',g1:'1º ano',g2:'2º ano',g3:'3º ano',g4:'4º ano',g5:'5º ano'};const modes={addition:'Adição',subtraction:'Subtração',multiplication:'Multiplicação',division:'Divisão',compare:'Comparação',sequence:'Sequências',missingNumber:'Número perdido',wordProblem:'Probleminhas',fraction:'Frações',mixed:'Desafio misto',boss:'Desafio final'};
function $(id){return document.getElementById(id)}
function show(id){['loading','authScreen','deniedScreen','dashboard'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
function esc(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}
function difficulty(p){const s=p.statsByMode||{};const arr=Object.entries(s).filter(([,v])=>v&&Number(v.questions)>0).map(([m,v])=>({mode:m,acc:Number(v.accuracy)||0,questions:Number(v.questions)||0}));if(!arr.length)return {label:'Sem dados',score:null,mode:null};arr.sort((a,b)=>a.acc-b.acc);const a=arr[0];return {label:a.acc<50?'Alta':a.acc<75?'Média':'Baixa',score:a.acc,mode:a.mode}}
async function isAdmin(user){const snap=await db.collection('admins').doc(user.uid).get();return snap.exists&&snap.data().role==='admin'}
async function login(){try{const provider=new firebase.auth.GoogleAuthProvider();await auth.signInWithPopup(provider)}catch(e){$('authMsg').textContent=e.message||'Não foi possível entrar com Google.'}}
async function load(){rows=[];for(const g of grades){const snap=await db.collection('mathQuestRanking').doc(g).collection('players').get();snap.forEach(d=>rows.push({id:d.id,...d.data(),grade:g}))}rows.sort((a,b)=>(Number(b.points)||0)-(Number(a.points)||0));$('updatedAt').textContent='Atualizado: '+new Date().toLocaleString('pt-BR');render()}
function filtered(){const g=$('gradeFilter').value,q=$('search').value.trim().toLowerCase();let a=rows.filter(p=>(g==='all'||p.grade===g)&&(!q||String(p.name||'').toLowerCase().includes(q)));const s=$('sortFilter').value;if(s==='accuracy')a.sort((x,y)=>(Number(y.lastAccuracy)||0)-(Number(x.lastAccuracy)||0));else if(s==='difficulty')a.sort((x,y)=>(difficulty(x).score??101)-(difficulty(y).score??101));else if(s==='level')a.sort((x,y)=>(Number(y.level)||0)-(Number(x.level)||0));else a.sort((x,y)=>(Number(y.points)||0)-(Number(x.points)||0));return a}
function render(){const a=filtered();const total=a.length,points=a.reduce((n,p)=>n+(Number(p.points)||0),0),accs=a.filter(p=>p.lastTotalQuestions).map(p=>Number(p.lastAccuracy)||0),avg=accs.length?Math.round(accs.reduce((x,y)=>x+y,0)/accs.length):0;const hard=a.filter(p=>difficulty(p).label==='Alta').length;const activeGrades=new Set(a.map(p=>p.grade)).size;$('stats').innerHTML=[['Alunos',total],['Pontos totais',points],['Precisão média',avg+'%'],['Com dificuldade alta',hard],['Turmas com dados',activeGrades]].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
$('rankingBody').innerHTML=a.slice(0,50).map((p,i)=>{const d=difficulty(p);return `<tr><td><b>${i+1}</b></td><td class="student">${esc(p.name||'Jogador')}</td><td><span class="pill">${labels[p.grade]||p.grade}</span></td><td>${Number(p.points)||0}</td><td>${Number(p.level)||1}</td><td class="${(Number(p.lastAccuracy)||0)>=70?'good':'bad'}">${Number(p.lastAccuracy)||0}%</td><td>${d.label}${d.mode?' · '+(modes[d.mode]||d.mode):''}</td></tr>`}).join('')||'<tr><td colspan="7">Nenhum dado encontrado.</td></tr>';
$('studentsBody').innerHTML=a.map(p=>{const d=difficulty(p);return `<tr><td class="student">${esc(p.name||'Jogador')}</td><td>${labels[p.grade]||p.grade}</td><td>${Number(p.points)||0}</td><td>${Number(p.lastCorrect)||0}</td><td>${Number(p.lastWrong)||0}</td><td>${Number(p.lastAccuracy)||0}%</td><td>${modes[p.lastMode]||p.lastMode||'—'}</td><td>${Number(p.lastBestCombo)||0}</td></tr>`}).join('')||'<tr><td colspan="8">Nenhum aluno encontrado.</td></tr>';
const diff={};a.forEach(p=>Object.entries(p.statsByMode||{}).forEach(([m,v])=>{if(!diff[m])diff[m]={q:0,c:0};diff[m].q+=Number(v.questions)||0;diff[m].c+=Number(v.correct)||0}));const da=Object.entries(diff).map(([m,v])=>({m,acc:v.q?Math.round(v.c/v.q*100):0,q:v.q})).sort((x,y)=>x.acc-y.acc);$('difficulty').innerHTML=da.length?da.map(x=>`<div class="diff-row"><div class="diff-top"><span>${modes[x.m]||x.m}</span><span>${x.acc}% · ${x.q} questões</span></div><div class="bar"><i style="width:${x.acc}%"></i></div></div>`).join(''):'<p class="small">Ainda não há dados suficientes.</p>';
const gs=grades.map(g=>{const ps=a.filter(p=>p.grade===g);const aa=ps.filter(p=>p.lastTotalQuestions).map(p=>Number(p.lastAccuracy)||0);return {g,n:ps.length,avg:aa.length?Math.round(aa.reduce((x,y)=>x+y,0)/aa.length):0,points:ps.reduce((n,p)=>n+(Number(p.points)||0),0)}});$('gradeCards').innerHTML=gs.map(x=>`<div class="grade-card"><h3>${labels[x.g]}</h3><p><b>${x.n}</b> alunos</p><p><b>${x.points}</b> pontos</p><p>Precisão média: <b>${x.avg}%</b></p></div>`).join('');}
$('gradeFilter').innerHTML='<option value="all">Todas as turmas</option>'+grades.map(g=>`<option value="${g}">${labels[g]}</option>`).join('');$('googleLogin').onclick=login;$('logout').onclick=()=>auth.signOut();$('logoutDenied').onclick=()=>auth.signOut();$('refresh').onclick=load;$('gradeFilter').onchange=render;$('sortFilter').onchange=render;$('search').oninput=render;
if(!cfg.apiKey){$('authMsg').textContent='Firebase não configurado.';show('authScreen');return}firebase.initializeApp(cfg);db=firebase.firestore();auth=firebase.auth();auth.onAuthStateChanged(async user=>{if(!user){show('authScreen');return}try{if(await isAdmin(user)){$('adminEmail').textContent=user.email||'';show('dashboard');await load()}else{$('deniedUid').textContent=user.uid;show('deniedScreen')}}catch(e){$('authMsg').textContent=e.message||'Erro ao verificar permissão.';show('authScreen')}});show('loading');
})();
